spring.application.name=belajar-springboot
server.port=8081

mail.smtp.host=sandbox.smtp.mailtrap.io
mail.smtp.port=25
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.trust=sandbox.smtp.mailtrap.io
mail.username=d1268cdd35952e
mail.password=34ff9375651117